"""Known-good validation rows from DATASET.md § Validation samples.

Each entry is keyed by morning date (YYYY-MM-DD) and contains the exact
expected column values. Tests assert within the tolerances in CLAUDE.md:
  ±0.1 for REAL columns (%, °C)
  ±1 for INTEGER columns (Wh)
"""

FIXTURES: dict[str, dict] = {
    # Feb 7, 2026 — AEDT, sunny, full battery, amber, curtailed
    "2026-02-07": {
        "provider": "amber",
        "absence_period": 0,
        "guests": None,  # sensor didn't exist until 2026-03-08
        "soc_at_6pm": 100.0,
        "min_soc_overnight": 73.9,
        "max_soc_prev_daylight": 100.0,
        "soc_at_11am": 98.9,
        "min_outdoor_temp": 17.6,
        "avg_indoor_temp": 21.7,
        "bom_temp_min": 15.3,
        "bom_temp_mean": 17.2,
        "bom_feels_like_min": 14.1,
        "bom_rain_max": 0.0,
        "bom_wind_mean": 10.3,
        "bom_gust_max": 32.0,
        "solcast_forecast_tomorrow_wh": 43973,
        "median_indoor_temp": 22.7,
        "bom_temp_max": 22.1,
        "bom_temp_afternoon_max": 23.5,
        "bom_humidity_mean": 74.5,
        "bom_humidity_max": 84.0,
        "median_indoor_humidity": 50.5,
        "solar_wh_before_11am": 9612,
        "consumption_wh_load": 4949,
        "grid_import_wh": 24,
        "grid_export_wh": 3635,
        "battery_charged_wh": 3600,
        "battery_discharged_wh": 3399,
        "evening_grid_export_wh": 1812,
        "consumption_wh": 5800,
        "curtailment_likely": 1,
    },
    # Mar 20, 2026 — AEDT, cloudy, deep discharge, amber, no curtailment
    "2026-03-20": {
        "provider": "amber",
        "absence_period": 0,
        "guests": 0,
        "soc_at_6pm": 63.2,
        "min_soc_overnight": 20.0,
        "max_soc_prev_daylight": 64.4,
        "soc_at_11am": 25.1,
        "min_outdoor_temp": 16.8,
        "avg_indoor_temp": 23.2,
        "bom_temp_min": 15.8,
        "bom_temp_mean": 17.0,
        "bom_feels_like_min": 15.0,
        "bom_rain_max": 0.4,
        "bom_wind_mean": 8.2,
        "bom_gust_max": 24.0,
        "solcast_forecast_tomorrow_wh": 34888,
        "median_indoor_temp": 22.3,
        "bom_temp_max": 18.6,
        "bom_temp_afternoon_max": 19.4,
        "bom_humidity_mean": 77.8,
        "bom_humidity_max": 86.0,
        "median_indoor_humidity": 60.0,
        "solar_wh_before_11am": 2779,
        "consumption_wh_load": 6624,
        "grid_import_wh": 768,
        "grid_export_wh": 6,
        "battery_charged_wh": 1360,
        "battery_discharged_wh": 5090,
        "evening_grid_export_wh": 0,
        "consumption_wh": 7271,
        "curtailment_likely": 0,
    },
    # Jul 17, 2025 — AEST, winter, depleted, ea, no curtailment
    "2025-07-17": {
        "provider": "ea",
        "absence_period": 0,
        "guests": None,  # sensor didn't exist until 2026-03-08
        "soc_at_6pm": 58.7,
        "min_soc_overnight": 6.5,
        "max_soc_prev_daylight": 65.7,
        "soc_at_11am": 6.5,
        "min_outdoor_temp": 10.0,
        "avg_indoor_temp": 19.4,
        "bom_temp_min": 9.2,
        "bom_temp_mean": 10.7,
        "bom_feels_like_min": 5.4,
        "bom_rain_max": 0.0,
        "bom_wind_mean": 17.4,
        "bom_gust_max": 41.0,
        "solcast_forecast_tomorrow_wh": 8789,
        "median_indoor_temp": 19.2,
        "bom_temp_max": 12.8,
        "bom_temp_afternoon_max": 15.0,
        "bom_humidity_mean": 80.6,
        "bom_humidity_max": 90.0,
        "median_indoor_humidity": 49.8,
        "solar_wh_before_11am": 1007,
        "consumption_wh_load": 13040,
        "grid_import_wh": 6731,
        "grid_export_wh": 1,
        "battery_charged_wh": 0,
        "battery_discharged_wh": 5806,
        "evening_grid_export_wh": 1,
        "consumption_wh": 13543,
        "curtailment_likely": 0,
    },
}

# Tolerances from CLAUDE.md
REAL_TOL = 0.1   # %, °C
WH_TOL = 1       # Wh
